# Generated by Django 4.0.3 on 2022-04-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Preferred_study_habits',
            new_name='preferred_study_habits',
        ),
        migrations.AddField(
            model_name='customer',
            name='study_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
